{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nvindex.fullname" . }}-auth-secret
  labels:
    {{- include "nvindex.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ htpasswd .Values.auth.username .Values.auth.password | b64enc }}
{{- end }}
