apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "nvindex.fullname" . }}-scenes"
  labels:
    {{- include "nvindex.labels" . | nindent 4 }}
data:
  {{- if .Values.scene }}
  {{- $scenePathGlob := printf "%s/**" .Values.scene -}}
  {{- range $path, $_ := ( .Files.Glob $scenePathGlob ) }}
  {{ base $path }}: |- {{ $.Files.Get $path | nindent 4 }}
  {{ end }}
  {{- end }}
