{{- if .Values.tls.base64EncodedPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-tls"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: viewer
type: Opaque
data:
  tls.key: |-
    {{ .Values.tls.base64EncodedPrivateKey | nindent 4 | trim }}
  tls.crt: |-
    {{ .Values.tls.base64EncodedCertificate | nindent 4 | trim }}
{{- end }}
