{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nvindex.fullname" . | quote -}}
{{- $svcName := (printf "%s-viewer" (include "nvindex.fullname" .)) -}}
{{- $svcPort := 8080 -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "nvindex.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: {{ printf "/%s" (include "nvindex.fullname" .) }}
          pathType: Prefix
          backend:
            service:
              name: {{ $svcName }}
              port:
                number: {{ $svcPort }}
    {{- end }}
