apiVersion: v1
kind: Service
metadata:
  name: "{{ include "nvindex.fullname" . }}-viewer"
  labels:
    {{- include "nvindex.labels" . | nindent 4 }}
    app.kubernetes.io/component: viewer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "nvindex.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: viewer
  type: ClusterIP

