apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-worker"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: worker
spec:
  replicas: {{ add .Values.nodeCount -1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}"
        app.kubernetes.io/component: worker
    spec:
      volumes:
        - name: rsync-config-files
          emptyDir: {}
        - name: setup-scripts
          configMap:
            name: setup-scripts
      initContainers:
        - name: setup
          image: {{ template "gcloudsdk.image" . }}
          volumeMounts:
            - name: setup-scripts
              mountPath: /setup
            - name: rsync-config-files
              mountPath: /config
          command: ['bash']
          args: ['/setup/setup_worker.sh']
      containers:
        - name: nvindex
          image: {{ template "nvindex.image" . }}
          command: [ './nvindex-remote-service.sh' ]
          args: [
            '--nogl',
            '--add', 'project_remote.prj',
            '-dice::network::mode', 'TCP_WITH_DISCOVERY',
            '-dice::network::retention', '5',
            '-app::enable_fail_safety', 'yes',
            '-dice::network::discovery_address', '{{ .Release.Name }}-viewer-0',
          ]
          env:
            - name: LICENSE_SEARCH_PATH
              value: "/config-external"
          volumeMounts:
          - name: rsync-config-files
            mountPath: /config
          ports:
          - containerPort: 5555
          - containerPort: 10000
          - containerPort: 10001
          resources:
            limits:
              nvidia.com/gpu: "{{ .Values.gpuCount }}"
{{- if .Values.debug }}
        - name: debug
          image: gcr.io/google-containers/toolbox
          command: ["bash"]
          args: ["-c", "while true; do sleep 60s; done"]
{{- end }}
