{{ if .Values.exposeWebSocket }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-ws"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: viewer
spec:
  ports:
  - name: global
    port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: viewer
  type: ClusterIP
{{ end }}
