apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-cluster"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: worker
spec:
  ports:
  - name: global
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: private
    port: 10001
    protocol: TCP
    targetPort: 10001
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: worker
  type: ClusterIP

