apiVersion: v1
kind: Service
metadata:
  name:  "{{ .Release.Name }}-viewer-0"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: viewer
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: discovery
    port: 5555
    protocol: TCP
    targetPort: 5555
  - name: global
    port: 10000
    targetPort: 10000
    protocol: TCP
  - name: local
    port: 10001
    targetPort: 10001
    protocol: TCP
  - name: debug
    port: 12345
    targetPort: 12345
    protocol: TCP
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: viewer
