{{- if .Values.viewerGeneratedPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-password"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: viewer
type: Opaque
data:
  viewer-password: {{ .Values.viewerGeneratedPassword | b64enc }}
{{- end }}
