## EKS specific presets

## NVIDIA IndeX container path
nvindex:
  image:
    registry: 709825985650.dkr.ecr.us-east-1.amazonaws.com
    repository: ingram-micro/185367027512.dkr.ecr.us-east-1.amazonaws.com/nvindex
    tag: 359600.1414-5
    pullPolicy: IfNotPresent
    secret: "nvindexcr"
  config:
    allowedOrigins: ""

# Cloud helper
cloudhelper:
  image:
    registry: docker.io 
    repository: amazon/aws-cli 
    tag: latest
    pullPolicy: IfNotPresent

debughelper:
  image:
    registry: docker.io 
    repository: amazon/aws-cli 
    tag: latest
    pullPolicy: IfNotPresent

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  name: nvindex-access

dataLocation: s3://nvindex-datasets-us-west2/scenes
