## Customizable fields:

# How many nodes to use for this session?
nodeCount: 1
# How many GPUs does one node have?
gpuCount: 1

# Path to scene dir, relative to chart dir.
#scene: scenes/00-supernova_ncsa_small
scene:

importThreads:

# Debug adds a side container for investigating
debug: false

## Non-customizable fiels

name: nvindex
publishedVersion: '2.3.1'

# NVIDIA IndeX container path
nvindex:
  image:
    registry: 185367027512.dkr.ecr.us-east-1.amazonaws.com
    repository: nvindex
    tag: 360141
    pullPolicy: IfNotPresent
    secret: "nvindexcr"
  config:
    allowedOrigins: ""

# Cloud helper
cloudhelper:
  image:
    registry: mcr.microsoft.com
    repository: azure-cli
    tag: latest
    pullPolicy: IfNotPresent

debughelper:
  image:
    registry: mcr.microsoft.com
    repository: azure-cli
    tag: latest
    pullPolicy: IfNotPresent

auth:
  enabled: true
  username: nvindex
  password: test123

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: nvindex-basic-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
  host: TODO.us-east-1.elb.amazonaws.com
  tls:
    secretName: ingress-tls-secret

nameOverride: ""
fullnameOverride: ""
